### ISSUE TITLE
Create new resource to manage environment overrides

### ISSUE THREAD

**Issue by asheynkmantyler** [harness/terraform-provider-harness#133]
Hello,

We have a slight design problem with current harness provider.

We are utilizing a design patter, by which we store all Harness asset configuration together with the code for the service itself. So for example service A has terraform configuration for Harness assets (service definition, environment values override) belonging to service A, service B has terraform definitions for service B. and so forth. 

That pattern breaks when it is applied to lambda services. The reason it breaks down, is because the only way to specify variable overrides for lambda service is for them to be part of harness_environment resource. So, the flow becomes like this:

1. Create harness environment in independent terraform workspace.
2. Create/adjust lambda services.
3. Go back to environment and create overrides.

To me at least, this pattern is slightly counterintuitive. To remediate this i would like to propose creation of new resource (lets call it harness_environment_override) that would be able to create/manage specific overrides for specific environment. It would look something like this:

```hcl
resource "harness_enviroment_override" "this" {
  app_id = <appid>
  environment_id=<environment id>
  override = {
     name = "foo1"
     type = "TEXT"
     value = "value1"
  }
  override = {
     name = "foo2"
     type = "TEXT"
     value = "value2"
  }
 and so forth

} 
```

I think that will make environment override management more flexible.

thanks,

Albert Sheynman

**Comment by micahlmartin** [comment]
Hi @asheynkmantyler . Thanks for sending this in. The challenge here is that for variable overrides in an environment, they're all managed inside the same config-as-code file in harness. It looks like this:

```
harnessApiVersion: '1.0'
type: ENVIRONMENT
configMapYamlByServiceTemplateName: {}
environmentType: NON_PROD
variableOverrides:
- name: testing
  value: foo
  valueType: TEXT
- name: cpu
  serviceName: ecs-example
  value: test
  valueType: TEXT
```

Under the hood, all I'm doing in Terraform is generating this yaml entity and pushing it to the API. I'm not sure how I can have separate resources manage separate parts of the same content file. Open to ideas!
