### ISSUE TITLE
Trigger not updated after successful Apply

### ISSUE THREAD

**Issue by spotys** [harness/terraform-provider-harness#414]
The terraform provider did not apply a change to a trigger (approvers user group has changed) even though the the terraform apply returned success.

### Terraform Version
1.3.6

### Affected Resource(s)
Please list the resources as a list, for example:
- harness_platform_triggers

### Debug Output
```
Terraform will perform the following actions:

  # harness_platform_triggers.main will be updated in-place
  ~ resource "harness_platform_triggers" "main" {
        id         = "main"
        name       = "main"
      ~ yaml       = <<-EOT
            trigger:
              name: main
              identifier: main
              enabled: true
              orgIdentifier: ClickUp
              projectIdentifier: terraformharnessplatformmgmt
              pipelineIdentifier: main
              source:
                type: Webhook
                spec:
                  type: Github
                  spec:
                    type: Push
                    spec:
                      connectorRef: main
                      autoAbortPreviousExecutions: false
                      payloadConditions: []
                      headerConditions: []
                      actions: []
              inputYaml: |
                pipeline:
                  identifier: main
                  stages:
                    - stage:
                        identifier: Terraform
                        type: Custom
                        spec:
                          execution:
                            steps:
                              - step:
                                  identifier: TerraformPlan
                                  type: TerraformPlan
                                  spec:
                                    configuration:
                                      configFiles:
                                        store:
                                          type: Github
                                          spec:
                                            branch: <+trigger.branch>
                              - step:
                                  identifier: HarnessApproval
                                  type: HarnessApproval
                                  spec:
                                    approvers:
                                      userGroups:
          -                             - account.DevOps
          +                             - account.Devops_Team
                  variables:
                    - name: AWS_Account_ID
                      type: String
                      value: "***"
                    - name: Repo_Name
                      type: String
                      value: terraform-harness-platform-mgmt
                    - name: Terraform_Target_Dir
                      type: String
                      value: targets/harness-pipelines
                    - name: Git_Branch_Name
                      type: String
                      value: <+trigger.branch>
        EOT
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
harness_platform_triggers.main: Modifying... [id=main]
harness_platform_triggers.main: Modifications complete after 0s [id=main]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behavior
The plan successfully applies.

### Actual Behavior
The plan applies, but the target resource is not changed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. have a trigger created by the TF provider
2. change approvers group in your TF script
3. run plan/apply
4. terraform applies the change and returns success
5. open the trigger in Harness and check the value
6. **BUG**: the old value still in place

### Important Factoids
I don't see anything unusual. Changes to other resources work fine. Just this one did not update after I changed the approvers within the trigger.
