### ISSUE TITLE
Trigger for helm chart not supported by provider

### ISSUE THREAD

**Issue by janario** [harness/terraform-provider-harness#592]
From the documentation https://developer.harness.io/docs/platform/Triggers/trigger-pipelines-on-new-helm-chart

I have generated it manually and tried to port it to the terraform.

From the UI it generates something like:

```
trigger:
  name: release-chart
  identifier: releasechart
  enabled: true
  tags: {}
  orgIdentifier: ci
  projectIdentifier: infra
  pipelineIdentifier: <my-pipeline>
  source:
    type: Manifest
    spec:
      type: HelmChart
      spec:
        store:
          type: Http
          spec:
            connectorRef: account.<helm>
        helmVersion: V3
        chartName: <chart_name>
        eventConditions: []
  inputYaml: |
    pipeline:
      identifier: <pipeline>
      stages:
        - stage:
            identifier: ci
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: NativeHelm
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: release
                          sources:
                            - identifier: release
                              type: CustomArtifact
                              spec:
                                version: <+trigger.manifest.version>
```

But when try with terraform for the similar template it gives an error:

```
╷
│ Error: Invalid request: Failed while Saving Trigger: Cannot deserialize value of type `io.harness.ngtriggers.beans.source.artifact.ArtifactType` from String "Manifest": not one of the values accepted for Enum class: [GithubPackageRegistry, ArtifactoryRegistry, CustomArtifact, AmazonS3, GoogleArtifactRegistry, Acr, Nexus3Registry, AzureArtifacts, Ecr, Jenkins, AmazonMachineImage, DockerRegistry, GoogleCloudStorage, Nexus2Registry, Bamboo, Gcr]
│  at [Source: (StringReader); line: 27, column: 3] (through reference chain: io.harness.ngtriggers.beans.config.NGTriggerConfigV2["source"]->io.harness.ngtriggers.beans.source.artifact.ArtifactTriggerConfig["type"])
│
```

### Terraform Version

```
Terraform v1.5.0
on darwin_arm64
+ provider registry.terraform.io/harness/harness v0.22.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- harness_platform_triggers

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234
